### ISSUE TITLE
stream doc tests are now disabled

### ISSUE THREAD

**Issue by montekki** [async-rs/async-std#235]
Looks like they are no longer run since 73d7fea9 but they probably should be. At least in [CI](https://travis-ci.com/async-rs/async-std/jobs/237994862) they are gone.

**Comment by yoshuawuyts** [comment]
Tagging in @stjepang

**Comment by stjepang** [comment]
So the problem here is that if `#[cfg(feature = "docs")]`, then we're using the following signature:

```rust
fn read_line<'a>(&'a mut self, buf: &'a mut String) -> ImplFuture<'a, io::Result<usize>>;
```

Otherwise, the signature is:

```rust
fn read_line<'a>(&'a mut self, buf: &'a mut String) -> ReadLine<'a, Self>;
```

We only have docs for the former but not the latter. The doc tests are not run because we're running tests with `docs` feature disabled, and we can't run them with the feature enabled because the code is broken in that case.

This is unfortunate and I'm not sure what's the best solution here. What if we copied examples in docs into a test file so that they get tested?

**Comment by montekki** [comment]
What's handy about rust docs especially with the cases like stdlib is that you:
1) are always sure that that example works (unless it's marked as non-run)
2) can press a "run" button and jump into the playground and run/modify it yourself however you like
3) Probably something else I'm missing

I am not sure that can be achieved with copying to testfile or some similar non-mainstream way, can it?
