### ISSUE TITLE
Enable byteorder crate?

### ISSUE THREAD

**Issue by 0b01** [async-rs/async-std#288]
Maybe implement byteorder's trait extensions on async-std's Write and Read. Or even make an async-byteorder. Thanks for the great crate!

**Comment by yoshuawuyts** [comment]
@0b01 thanks for the suggestion; we're glad you're enjoying `async-std`! We currently have no plans to add byteorder extensions to `async-std`, but if you think that's something that's needed we encourage you to try doing it!

Alternatively you could consider opening an issue on `byteorder` to request extensions for [`futures_io_preview::{AsyncRead, AsyncWrite}`](https://docs.rs/futures-io-preview/0.3.0-alpha.19/futures_io). Because `async_std::io` re-uses the `futures-rs` trait definitions it'd work for us too!
