### ISSUE TITLE
async-std and futures-rs

### ISSUE THREAD

**Issue by kpp** [async-rs/async-std#360]
Hi all,

There are a lot of combinators copypasted from https://github.com/rust-lang-nursery/futures-rs/.

I would like to know your thoughts on further reducing the code in async-std in order to ease the maintenance and mitigate potential security risks.

**Comment by skade** [comment]
Hi @kpp, I'm sympathetic to de-duplicating that at some point, but we currently don't re-export from futures-rs in general because their stability guarantees are different and things are in flux. Once they commit on interfaces, that might change.

I'd be interested which _security risks_ you see in combinator implementations?

**Comment by laizy** [comment]
@kpp,  I think this function is safe, since `W` has `Unpin` constraint, and the field `reader` owns `R`. if `R` is `!Unpin`, then `CopyFuture` is `!Unpin`. So we can not get `&mut CopyFuture` from `Pin<&mut CopyFuture` to move out the `reader` field, we also can not get `&mut R` from `Pin<&mut R>`.  please correct me if I am wrong.

**Comment by yoshuawuyts** [comment]
@kpp our position on this hasn't changed since you raised this a few weeks ago. You can find it here: https://github.com/async-rs/async-std/pull/123#issuecomment-525916716

To re-iterate: `async-std` currently doesn't use the `futures-preview` crate, and we don't intend to either. We rely on `futures-core-preview` and `futures-io-preview` to provide ecosystem compatibility, and have no intention of changing our approach at this time.

Going to go ahead and close this since we've made our position clear on this.

**Comment by kpp** [comment]
@youshuawuyts actually your position is not clear to me. I can try to wrap the existent combinators into your stable api. So your api won’t change but it will reduce the inner code and copypaste a lot. Would it be acceptable to you?

**Comment by yoshuawuyts** [comment]
@kpp No thank you. `async-std` currently doesn't use the `futures-preview` crate, and we don't intend to either. We rely on `futures-core-preview` and `futures-io-preview` to provide ecosystem compatibility, and have no intention of changing our approach at this time.

**Comment by kpp** [comment]
May I ask the reason why you don't intend to use futures-preview?

**Comment by skade** [comment]
Because the name of the library is `preview` and the communicated state is `alpha`. The stability guarantees of `futures-preview` don't match ours and re-exporting `futures-preview` types is a stability hazard. This is both to allows the `futures-preview` team to do decisions without us, as much as the other way around. We are in close touch and track changes on both sides.

That may change when `futures-rs` stabilised, in which moment we'll also reconsider our position.

**Comment by kpp** [comment]
Thanks! That’s what I wanted to know.
