### ISSUE TITLE
Extend examples to show more than just a single `task::block_on`

### ISSUE THREAD

**Issue by brandonros** [async-rs/async-std#522]
Can somebody add an example of what this would look like:

```javascript
const foo = async function () { return 1 }
const bar = async function () { return 1 }
const results = await Promise.all([foo(), bar()])
```

I think having just a single `task::block_on` in each example isn't very "real world"

**Comment by yoshuawuyts** [comment]
@brandonros the equivalent with `async-std` would be:

```rust
use async_std::task;

async fn foo() -> u8 {
    1
}

async fn bar() -> u8 {
    1
}

fn main() {
    task::block_on(async {
        let results = foo().join(bar()).await;
    })
}
```

Or with the `"attributes"` feature enabled in `Cargo.toml`, and using closures, we can shorten it somewhat:

```rust
#[async_std::main]
async fn main() {
    let foo = || async move { 1 };
    let bar = || async move { 1 };
    let results = foo().join(bar()).await);
}
```

You're right tho, we should consider adding a larger example to our docs. Even if it's a single extra call, it might be useful for people new to async rust to see what it's like. Thanks for raising this!

**Comment by omac777** [comment]
I totally agree there should be more examples surrounding the task::block_on.

For example how do we pass in arguments into this task block?
Everything I attempted to pass in i.e. &str, &Vec<String> all give me compiler errors that the variables do not survive lifetime of variable at the close of the task block.  I don't mind that, but I need to pass data into it in order to make these task blocks useful.  Hard-coded strings are static and not useful as an example to use this stuff.

**Comment by stjepang** [comment]
@omac777 Can you provide an example of code that gives this lifetime error?
