### ISSUE TITLE
BufWriter not flushed

### ISSUE THREAD

**Issue by mtthw-meyer** [async-rs/async-std#586]
If you run the attached code, connect a client, and then terminate it the time stamp is not flushed to disk (as expected?). Adding an explicit call to flush() fixed it but seems like it should not be necessary.

https://gist.github.com/mtthw-meyer/34d85197e01d686dacca5cf1cd6b28b3

**Comment by yoshuawuyts** [comment]
@mtthw-meyer could you perhaps upload the code to github or put it in a gist? I'd rather not unzip files locally. Thanks!

**Comment by withoutboats** [comment]
I was just about to file an issue about the documentation being wrong. For now (until async destructors are possible) probably the best thing would be to change the documentation, which is currently inaccurate.

The docs state:

> When the BufWriter is dropped, the contents of its buffer will be written out. However, any errors that happen in the process of flushing the buffer when the writer is dropped will be ignored. Code that wishes to handle such errors must manually call flush before the writer is dropped.

This is true of std's BufWriter type, but not of async-std's type. async-std's type does nothing on Drop, and you have to explicitly call flush to flush it. This is not surprising: there's no way to yield from async operations in destructors, so it would have to spawn a new task or block this thread in order to implement this behavior.

The documentation should be changed to clarify that this type does nothing on Drop and users *must* call flush. For now.

The docs also contain this line:

>This type is an async version of std::io::BufReader.

This is definitely a typo and should instead refer to `std::io::BufWriter`.
