### ISSUE TITLE
Consider `split` method on TcpStream to create a reader and a writer instance

### ISSUE THREAD

**Issue by paulocsanz** [async-rs/async-std#657]
A reddit discussion about the current ergonomics of async ended up in a comparison of the straight-forward way a begginer may take to implement something async.

And people ended-up getting confused about the need for a `&mut &TcpStream` to write, so they ended up using Arc by mistake, this was pointed out days later (after a bunch of people upvoted the implementation with the useless Arc). So maybe this simple method would make the library more intuitive/ergonomic. This method is available in other async approaches and seem to be relied upon.

```
impl TcpStream {
    fn split(&self) -> (&Self, &Self) {
        (self, self)
    }
}
```

Discussion: https://www.reddit.com/r/rust/comments/ej649l/a_summary_of_the_current_state_of_async_rust/fdb4abw/

I can provide a PR, it's just so simple that it could be done without one. But if desired I will.

**Comment by yoshuawuyts** [comment]
@paulocsanz this would conflict with the [`BufRead::split`](https://docs.rs/async-std/1.4.0/async_std/io/trait.BufRead.html#method.split) method we already export (and has a counterpart in `std::io::BufRead::split`).

Using `Arc` is not *wrong* in many cases, and should have negligable performance overhead. However common cases such as `io::copy` may want a simpler path, which is why we're trying out more loose function bounds as part of "unstable" which should be easier to use e.g.

```rust
let stream = TcpStream::accept("localhost:8080").await?;
io::copy(&stream, &stream).await?;
```
