### ISSUE TITLE
impl Clone for DirEntry

### ISSUE THREAD

**Issue by arzg** [async-rs/async-std#669]
Thanks for async_std :)

**Comment by stjepang** [comment]
The sync version of `DirEntry` does not implement `Clone`, which is the reason why we didn't implement it either:
https://doc.rust-lang.org/nightly/std/fs/struct.DirEntry.html

But I suppose implementing `Clone` for our `DirEntry` wouldn't hurt. We can even derive the impl because our `DirEntry` wraps an `Arc<std::fs::DirEntry>`.

**Comment by arzg** [comment]
Sounds good!

**Comment by arzg** [comment]
Thanks.
