### ISSUE TITLE
Why does the version number jump from '0.1.0' to '0.99.x'? Is it misleading? Where does this confidence come from? This does not conform to the tradition of Rust！

### ISSUE THREAD

**Issue by danclive** [async-rs/async-std#67]
![aaaaa](https://user-images.githubusercontent.com/7814847/63208902-e78c2300-c10c-11e9-8f22-dfeeb9814445.png)

**Comment by danwilhelm** [comment]
This project (and Rust) follow semantic versioning. This often causes confusion, since many people believe that pre-1.0 indicates unstable software. However, in semantic versioning, pre-1.0 only indicates that the public API may change. (See points 4 and 5 here: https://semver.org/ -- particularly, "Version 1.0.0 defines the public API.")

@stjepang carefully notes that the library is very close to a stable API in the release post. "[async-std] will soon provide a stable interface to base your async libraries and applications on. While we don't promise API stability before our 1.0 release, we also don't expect to make any breaking changes." [1]

Aside from this, note that the versioning speed could also be justified (relative to other Rust libraries) because async-std is "mimicking [the] standard library's well-understood APIs as closely as possible." [1] This alone indicates that a stable public API might be achievable earlier than in other projects, since it must conform to the standard library's pre-existing public API.

[1] https://async.rs/blog/announcing-async-std/#
