### ISSUE TITLE
[Question] future::timeout vs io::timeout

### ISSUE THREAD

**Issue by goto-bus-stop** [async-rs/async-std#725]
There are two timeout functions: `future::timeout` and `io::timeout`. The documentation says that I should consider `io::timeout` for "I/O futures" but `future::timeout` for other futures.

Is there something special about "I/O futures" that requires that the other `timeout` fn is used, or is it only about the resulting error type?

**Comment by yoshuawuyts** [comment]
@goto-bus-stop `io::timeout` returns an `io::Error` on failure which means the return type is `io::Result<T>`. `future::timeout` returns a different error so when used with an IO type the return type is `Result<io::Result<T>>`. This means that in order to unwrap it you need to call `.await??` on it which looks a bit weird. So `io::timeout` is nicer for the cases where you know you're dealing with `io::Result`.

Hope this is helpful!
