### ISSUE TITLE
async vs multithreading

### ISSUE THREAD

**Issue by thomas-hugel** [async-rs/async-std#750]
Hello,

In the book section «Sending messages», you write:

> if Alice sends bob: foo , and Charley sends bob: bar , Bob might actually receive fobaor . Sending a message over a socket might require several syscalls, so two concurrent .write_all 's might interfere with each other!

> As a rule of thumb, only a single task should write to each TcpStream.

Then you resort to an Arc to share access to the TcpStream, and to a mpsc channel to have only one task writing to the socket.

I get confused: why in an async environment should we need to use thread-specific constructs? Doesn't it completely defeat the purpose of async programming? Why should data races occur in an async framework? Isn't the event loop supposed to treat one action after the other?

Thanks for your help!

**Comment by thomas-hugel** [comment]
Thank you for your answer. I still have questions:
1. Would there be the same problem on a single-theaded event loop like Node.js? If so, what solution would be relevant on Node.js?
2. In Rust, if we split the TcpStream into reader and writer, is it possible to have only message passing and no sharing at all (no Arc)? (listener -> mspc -> broker -> writer)
3. Wouldn't it be simpler to implement this chat using good old threads and mutexes?

**Comment by asonix** [comment]
1. I think node js's implementation of async/await might not have this issue (but don't quote me on that). Rather than using polling on tasks to make progress, Node JS uses a callback style approach to handle operations.

2. I think that should be possible. If the same task is doing both the reading and the writing, you don't need to put it in an Arc. If you do end up splitting the read task and write task, you'll still need an Arc because it's possible that the reader & writer would live on different "real" threads.

3. It might be! You could try an async mutex approach as well with [futures' mutex](https://docs.rs/futures/0.3.4/futures/lock/struct.Mutex.html). That said, you'd likely get better performance out of an async version, since you're not spawning threads & context switching for each connection.

**Comment by GopherJ** [comment]
I think maybe:
1. No. event-loop call callback one by one. There won't be two callbacks being called at the same time.

3. async's advantage over threads is to have a thread pool to avoid having too much threads. If you are using thread pool, you may achieve similar result.

**Comment by thomas-hugel** [comment]
Still one question: why do you spend so much effort building an async framework rather than green threads? It seems to me that they would bring both simplicity and performance, as the Go language shows it.

**Comment by extraymond** [comment]
> Still one question: why do you spend so much effort building an async framework rather than green threads? It seems to me that they would bring both simplicity and performance, as the Go language shows it.

I found this [talk](https://www.youtube.com/watch?v=lJ3NC-R3gSI) by Steve which talks about whether to implement  green thread or not. 

I believe it's chosen because rust wants to stay at the system language level where user have access to tweak about the underlying mechanism while providing zero cost abstraction.

**Comment by jimblandy** [comment]
@thomas-hugel As it turns out, synchronization problems do show up in node.js and web browsers, and will arise in any language with asynchronous features. They're introduced, not by threads, but by callbacks and awaits.

JavaScript only runs one event handler at a time. But consider an event handler like this:
```
function handle_click(event) {
  fetch('http://example.com/movies.json')
    .then(response => response.json())
    .then(data => console.log(data));
}
```

Depending on how long the promise that `fetch` returns takes to resolve, any number of other event handlers could run between the time this function is called and the time that we log the result to the console. This example is simple, but if the event handler wanted to actually have an effect on the page's state (as one usually does), it must be carefully written to tolerate other event handlers' effects on the page jumping in while it is waiting for promises to resolve. Perhaps all its effects must be put off until the very last callback. Perhaps other events will need to wait for this operation to finish before they can proceed. But these problems are very similar to those that threaded synchronization primitives like channels and mutexes are designed to solve: ensuring that things happen in an acceptable order.

It's true that you can assume you won't be interrupted in the middle of ordinary JavaScript control flow - it's only `await` expressions and callbacks that make it possible for other code to interrupt. But you must carefully restrict which functions you use within your "critical sections", to ensure that nobody starts an asynchronous operation. Most complex interactive JavaScript applications introduce some sort of rules or constructs for dealing with this.

One of your broader assumptions seems to be that 'the purpose of async programming' is to be a programming model that avoids the complexities of multi-threaded programming. It's true that asynchronous features play this role in JavaScript: they bring a certain kind of pleasant concurrency to the language without having to go fully threaded, which would be extremely difficult not just for developers but also for implementers of the language.

But this doesn't apply in Rust, for two reasons:

1) Multi-threaded programming is not worth avoiding in Rust. It is not at all like multi-threaded programming in any other production language. Once your program compiles, it is free of data races. You can use threads in Rust whenever they make sense, just as you would decide to use a `for` loop. Channels and mutexes and arcs are not hard to get used to, and the language will catch whatever mistakes you make in the learning process.

2) The value of asynchronous programming in Rust is its performance in certain cases. Operating system threads have certain kinds of overhead that make them unsuitable for certain sorts of work. On Linux, an operating system thread takes 15µs to start, and uses around 20KiB at minimum. Rust can start an asynchronous task fifty times faster than that, and it will use only as much memory as it needs to suspend itself at its await points. So if your program is bound by the speed of task creation and per-task memory consumption (not all are!), then you can go much farther on a given piece of hardware with asynchronous code.

So in fact, asynchronous programming in Rust has been designed from the start to be used *together* with threads: you'll usually see a pool of threads all running asynchronous tasks. So an async task might migrate from one thread to another over the course of its execution, and will certainly run concurrently with other tasks. This is why crates like `async-std` and `tokio` include full suites of synchronization tools like channels and mutexes.

**Comment by jimblandy** [comment]
I recommend Steve's talk, too. Rust had green threads originally, but then took them out because they have certain kinds of overhead that we can't ameliorate the way Go does.

**Comment by thomas-hugel** [comment]
Many thanks for your answers.
I have watched the talk by Steve Klabnik and I understand why the Rust language doesn't offer green threads.
But, I still cannot understand why green threads should not be available as an extra library for the people who can afford a little extra runtime. Wouldn't their performance be comparable to what async libraries achieve? Why not?
As for the art of programming, Bob Nystrom emphasizes that async inevitably brings a kind of apartheid between sync and async functions (red and blue functions). Every function shall have two versions, just like async-std has to mimic all functions from std.
Here is his article : https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/

**Comment by thomas-hugel** [comment]
I did a simple benchmark, scanning 500 TCP ports on a remote host. Here are my results:
- sequential : 247 s;
- parallel iterators from rayon : 68 s;
- async-std : 42 s;
- tokio : 42 s;
- 1 native thread / port : 42 s;
- a pool of 30 threads from rayon : 10 s.

**Comment by jimblandy** [comment]
Those results are not surprising. Threads are very efficient, and are fine for almost all applications. Async has an advantage when your program is limited by the speed of task creation, or your tasks are relatively small and you want to run as many as possible. Your benchmark doesn't meet either of those criteria, so threads should have the advantage.

There are a number of green thread crates: https://lib.rs/keywords/green
Why not give them a try?

I think it's unhelpful to bring emotionally charged words like 'apartheid' or (in the US at least) 'red and blue' into a technical discussion, because it invites us to view technical opinions as reflections of individual character, instead of problems that can be analyzed and understood.

That said, yes, I think it's unfortunate that async-std and tokio need to reimplement std's functionality. The fact that it's been done twice is even more unfortunate. But remember that basing your language on green threads doesn't change this: it just picks a winner, making the async library the default. Rust picked sync as the winner. As far as I can see, async has a much smaller (but still important!) niche, so I think Rust made the right choice.

**Comment by GopherJ** [comment]
@thomas-hugel This RFC may help to understand: https://github.com/rust-lang/rfcs/blob/0806be4f282144cfcd55b1d20284b43f87cbe1c6/text/0230-remove-runtime.md

**Comment by thomas-hugel** [comment]
Thanks for your answers.
